{% set name = "eth-abi" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eth_abi-{{ version }}.tar.gz
  sha256: 33ddd756206e90f7ddff1330cc8cac4aa411a824fe779314a0a52abea2c8fc14

build:
  skip: True  # [py<39 or py>311]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - eth-typing >=3.0.0
    - eth-utils >=2.0.0
    - parsimonious >=0.10.0,<0.11.0
    - python

test:
  imports:
    - eth_abi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-abi
  summary: 'eth_abi: Python utilities for working with Ethereum ABI definitions, especially encoding and decoding'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ethereum/eth-abi
  doc_url: https://eth-abi.readthedocs.io/
  description: |
    Python utilities for working with Ethereum ABI definitions, especially encoding and decoding.

extra:
  recipe-maintainers:
    - step21
